name: GameStore Deploy

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prepare WordPress Zip
        run: |
          WP_LINK=$(cat wp-version-control.cfg)
          wget -O "./wordpress.zip" $WP_LINK

      - name: Prepare plugins and theme zip
        run: zip -r wpcontent.zip plugins mu-plugins themes

      - name: Copy Zips to Server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./wordpress.zip, ./wpcontent.zip"
          target: ${{ github.event_name == 'push' && '/var/www/html/dev_folder' || '/var/www/html/prod_folder' }}

      - name: Enable Maintenance Mode
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: ".maintenance"
          target: ${{ github.event_name == 'push' && '/var/www/html/dev_folder' || '/var/www/html/prod_folder' }}

      - name: Update WordPress Core
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
              find "/var/www/html/dev_folder" -type f -name "*.php" ! -name "wp-config.php" -delete
              rm -r "/var/www/html/dev_folder/wp-admin/" "/var/www/html/dev_folder/wp-includes/"
              unzip -o "/var/www/html/dev_folder/wordpress.zip" -d "/var/www/html/dev_folder/"
              mv "/var/www/html/dev_folder/wordpress"/* "/var/www/html/dev_folder/"
              rm -r "/var/www/html/dev_folder/wordpress"

      - name: Update Plugins and Theme
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf "${{ github.event_name == 'push' && '/var/www/html/dev_folder' || '/var/www/html/prod_folder' }}/wp-content/plugins" "${{ github.event_name == 'push' && '/var/www/html/dev_folder' || '/var/www/html/prod_folder' }}/wp-content/mu-plugins" "${{ github.event_name == 'push' && '/var/www/html/dev_folder' || '/var/www/html/prod_folder' }}/wp-content/themes"
            unzip -o "${{ github.event_name == 'push' && '/var/www/html/dev_folder' || '/var/www/html/prod_folder' }}/wpcontent.zip" -d "${{ github.event_name == 'push' && '/var/www/html/dev_folder' || '/var/www/html/prod_folder' }}/wp-content/"

      - name: Disable Maintenance Mode and Remove zips
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -f "${{ github.event_name == 'push' && '/var/www/html/dev_folder' || '/var/www/html/prod_folder' }}/.maintenance"
            rm -f "${{ github.event_name == 'push' && '/var/www/html/dev_folder' || '/var/www/html/prod_folder' }}/wpcontent.zip"
            rm -f "${{ github.event_name == 'push' && '/var/www/html/dev_folder' || '/var/www/html/prod_folder' }}/wordpress.zip"
